# 분석 목적, 방법, 결과

## 분석 목적

이 노트북의 목적은 fastText로 만든 threshold별 ESG 단어 확장 사전이 seed dictionary보다 KCGS ESG 등급과의 통계적 연관성을 개선하는지 검증하는 것이다.

## 분석 방법

1. DART 사업보고서의 `II. 사업의 내용`, `IV. 이사의 경영진단 및 분석의견`, `VI. 이사회 등 회사의 기관에 관한 사항` 텍스트를 기업-연도 단위 document로 구성했다.
2. seed dictionary와 threshold별 expanded dictionary(`0.55`, `0.60`, `0.65`, `0.70`, `0.80`)를 같은 corpus에 적용했다.
3. 각 사전별로 `count`, `count_tfidf_score`, `presence_count`, `presence_tfidf_score`, `share` feature를 생성했다.
4. 각 expanded dictionary feature와 KCGS ESG 등급 사이의 Spearman 상관을 계산하고, 같은 metric의 seed dictionary 결과와 비교했다.
5. `rho - seed`를 기준으로 확장 사전의 개선 여부를 확인했다.
6. `total_word_count`를 통제한 OLS 회귀로 확장 사전 feature와 ESG 등급의 관계를 추가 검증했다.

## 분석 결과

## Spearman 결과

| metric | dictionary | threshold | feature | n | Spearman rho | seed rho | rho - seed | p-value |
|---|---|---:|---|---:|---:|---:|---:|---:|
| count | expanded_0_80 | 0.80 | ESG_expanded_0_80_count | 378 | 0.719860 | 0.719860 | 0.000000 | 1.364310e-61 |
| count_tfidf_score | expanded_0_80 | 0.80 | ESG_expanded_0_80_count_tfidf_score | 378 | 0.719589 | 0.719589 | 0.000000 | 1.589053e-61 |
| presence_count | expanded_0_60 | 0.60 | ESG_expanded_0_60_presence_count | 378 | 0.650867 | 0.605798 | 0.045069 | 6.475150e-47 |
| presence_tfidf_score | expanded_0_60 | 0.60 | ESG_expanded_0_60_presence_tfidf_score | 378 | 0.628180 | 0.602705 | 0.025475 | 6.868036e-43 |
| share | expanded_0_65 | 0.65 | ESG_expanded_0_65_share | 378 | 0.046866 | 0.032721 | 0.014144 | 3.635309e-01 |

## OLS 결과

| metric | dictionary | threshold | feature | n | coef | std_err | p-value | R2 | word_count_coef | word_count_p |
|---|---|---:|---|---:|---:|---:|---:|---:|---:|---:|
| count | expanded_0_60 | 0.60 | ESG_expanded_0_60_count | 378 | 1.006010 | 0.117103 | 8.634836e-18 | 0.382686 | -0.011815 | 0.904065 |
| count | expanded_0_65 | 0.65 | ESG_expanded_0_65_count | 378 | 1.024020 | 0.126535 | 5.833080e-16 | 0.380763 | -0.037394 | 0.713712 |
| count | expanded_0_55 | 0.55 | ESG_expanded_0_55_count | 378 | 1.044272 | 0.124661 | 5.434185e-17 | 0.375359 | -0.070611 | 0.497158 |
| count | expanded_0_70 | 0.70 | ESG_expanded_0_70_count | 378 | 0.970092 | 0.147319 | 4.549075e-11 | 0.362589 | 0.000041 | 0.999682 |
| count | seed |  | ESG_seed_count | 378 | 0.963747 | 0.155308 | 5.456405e-10 | 0.360978 | 0.005193 | 0.959958 |
| count | expanded_0_80 | 0.80 | ESG_expanded_0_80_count | 378 | 0.963747 | 0.155308 | 5.456405e-10 | 0.360978 | 0.005193 | 0.959958 |
| count_tfidf_score | expanded_0_60 | 0.60 | ESG_expanded_0_60_count_tfidf_score | 378 | 0.819726 | 0.130488 | 3.341963e-10 | 0.333053 | 0.133539 | 0.150758 |
| count_tfidf_score | expanded_0_65 | 0.65 | ESG_expanded_0_65_count_tfidf_score | 378 | 0.826557 | 0.142989 | 7.445022e-09 | 0.332237 | 0.123401 | 0.200644 |
| count_tfidf_score | expanded_0_55 | 0.55 | ESG_expanded_0_55_count_tfidf_score | 378 | 0.820251 | 0.145119 | 1.583467e-08 | 0.317589 | 0.102916 | 0.289966 |
| count_tfidf_score | expanded_0_70 | 0.70 | ESG_expanded_0_70_count_tfidf_score | 378 | 0.751186 | 0.156998 | 1.712510e-06 | 0.316774 | 0.185617 | 0.056146 |
| count_tfidf_score | seed |  | ESG_seed_count_tfidf_score | 378 | 0.751459 | 0.175742 | 1.903371e-05 | 0.315863 | 0.183318 | 0.077756 |
| count_tfidf_score | expanded_0_80 | 0.80 | ESG_expanded_0_80_count_tfidf_score | 378 | 0.751459 | 0.175742 | 1.903371e-05 | 0.315863 | 0.183318 | 0.077756 |
| presence_count | expanded_0_70 | 0.70 | ESG_expanded_0_70_presence_count | 378 | 0.847571 | 0.073997 | 2.240803e-30 | 0.389967 | 0.216198 | 0.011405 |
| presence_count | expanded_0_60 | 0.60 | ESG_expanded_0_60_presence_count | 378 | 0.896164 | 0.082146 | 1.038903e-27 | 0.383357 | 0.133088 | 0.149152 |
| presence_count | expanded_0_65 | 0.65 | ESG_expanded_0_65_presence_count | 378 | 0.845586 | 0.078949 | 9.084513e-27 | 0.380414 | 0.197741 | 0.025097 |
| presence_count | seed |  | ESG_seed_presence_count | 378 | 0.756565 | 0.076555 | 4.951162e-23 | 0.359741 | 0.278706 | 0.001320 |
| presence_count | expanded_0_80 | 0.80 | ESG_expanded_0_80_presence_count | 378 | 0.756565 | 0.076555 | 4.951162e-23 | 0.359741 | 0.278706 | 0.001320 |
| presence_count | expanded_0_55 | 0.55 | ESG_expanded_0_55_presence_count | 378 | 0.854464 | 0.098368 | 3.741073e-18 | 0.344278 | 0.111719 | 0.263040 |
| presence_tfidf_score | expanded_0_70 | 0.70 | ESG_expanded_0_70_presence_tfidf_score | 378 | 0.723830 | 0.080459 | 2.334573e-19 | 0.346887 | 0.293762 | 0.000584 |
| presence_tfidf_score | seed |  | ESG_seed_presence_tfidf_score | 378 | 0.721783 | 0.079677 | 1.318803e-19 | 0.339722 | 0.278175 | 0.001617 |
| presence_tfidf_score | expanded_0_80 | 0.80 | ESG_expanded_0_80_presence_tfidf_score | 378 | 0.721783 | 0.079677 | 1.318803e-19 | 0.339722 | 0.278175 | 0.001617 |
| presence_tfidf_score | expanded_0_65 | 0.65 | ESG_expanded_0_65_presence_tfidf_score | 378 | 0.685948 | 0.093185 | 1.822972e-13 | 0.327244 | 0.296217 | 0.000690 |
| presence_tfidf_score | expanded_0_60 | 0.60 | ESG_expanded_0_60_presence_tfidf_score | 378 | 0.719746 | 0.099096 | 3.783211e-13 | 0.323219 | 0.240415 | 0.010349 |
| presence_tfidf_score | expanded_0_55 | 0.55 | ESG_expanded_0_55_presence_tfidf_score | 378 | 0.613167 | 0.115357 | 1.064367e-07 | 0.288649 | 0.290525 | 0.004330 |

In [1]:
import subprocess
import sys
from pathlib import Path
import re
import html
import unicodedata
import warnings

subprocess.check_call([
    sys.executable,
    "-m",
    "pip",
    "install",
    "-q",
    "pandas",
    "numpy",
    "scikit-learn",
    "scipy",
    "statsmodels",
])

import numpy as np
import pandas as pd
from IPython.display import display

warnings.filterwarnings("ignore")
pd.set_option("display.max_colwidth", 160)
pd.set_option("display.max_rows", 120)

print("packages loaded")

packages loaded

In [2]:
# Path setup: supports both Colab and local execution.
if Path("/content").exists():
    from google.colab import drive
    drive.mount("/content/drive")

LOCAL_ROOT = Path.cwd()
DRIVE_ROOT_CANDIDATES = [
    Path("/content/drive/MyDrive/UD_26"),
    Path("/content/drive/My Drive/UD_26"),
]
ROOT_CANDIDATES = DRIVE_ROOT_CANDIDATES + [LOCAL_ROOT, LOCAL_ROOT.parent]


def first_existing(candidates, default=None):
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return default if default is not None else candidates[0]


ROOT = first_existing(
    [p for p in ROOT_CANDIDATES if (p / "data").exists() or (p / "final").exists()],
    LOCAL_ROOT,
)

FINAL_DIR = ROOT / "final"
DATA_DIR = ROOT / "data"
DART_DIR = DATA_DIR / "dart"

COMPANY_MASTER_PATH = first_existing([
    DATA_DIR / "company_master.csv",
    FINAL_DIR / "company_master.csv",
])

FILING_INDEX_PATH = first_existing([
    DART_DIR / "filing_index.csv",
    FINAL_DIR / "filing_index.csv",
    DATA_DIR / "filing_index.csv",
])

RAW_XML_DIR = first_existing([
    DART_DIR / "raw_xml",
    FINAL_DIR / "raw_xml",
    ROOT / "raw_xml",
])

SEED_DICTIONARY_PATH = first_existing([
    FINAL_DIR / "seed_dictionary.csv",
    DATA_DIR / "seed_dictionary.csv",
])

EXPANDED_OUTPUT_DIR = FINAL_DIR / "expanded_dictionaries"
EXPANDED_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

for label, path in {
    "ROOT": ROOT,
    "COMPANY_MASTER_PATH": COMPANY_MASTER_PATH,
    "FILING_INDEX_PATH": FILING_INDEX_PATH,
    "RAW_XML_DIR": RAW_XML_DIR,
    "SEED_DICTIONARY_PATH": SEED_DICTIONARY_PATH,
    "EXPANDED_OUTPUT_DIR": EXPANDED_OUTPUT_DIR,
}.items():
    print(f"{label}: {path} | {'OK' if path.exists() or label == 'EXPANDED_OUTPUT_DIR' else 'MISSING'}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
ROOT: /content/drive/MyDrive/UD_26 | OK
COMPANY_MASTER_PATH: /content/drive/MyDrive/UD_26/data/company_master.csv | OK
FILING_INDEX_PATH: /content/drive/MyDrive/UD_26/final/filing_index.csv | OK
RAW_XML_DIR: /content/drive/MyDrive/UD_26/final/raw_xml | OK
SEED_DICTIONARY_PATH: /content/drive/MyDrive/UD_26/final/seed_dictionary.csv | OK
EXPANDED_OUTPUT_DIR: /content/drive/MyDrive/UD_26/final/expanded_dictionaries | OK

In [3]:
# Leave as None to score every expanded_dictionary_theta_*.csv file found in EXPANDED_OUTPUT_DIR.
# Set to a list such as [0.70, 0.75, 0.80] to restrict scoring to selected thresholds.
REQUESTED_THRESHOLDS = [0.55, 0.60, 0.65, 0.70, 0.80]

GRADE_MAP = {"D": 0, "C": 1, "B": 2, "B+": 3, "A": 4, "A+": 5, "S": 6}

print("REQUESTED_THRESHOLDS:", REQUESTED_THRESHOLDS if REQUESTED_THRESHOLDS is not None else "all available")

REQUESTED_THRESHOLDS: [0.55, 0.6, 0.65, 0.7, 0.8]

In [4]:
company_master = pd.read_csv(COMPANY_MASTER_PATH, dtype={"stock_code": "string"}, encoding="utf-8-sig")
filing_index = pd.read_csv(FILING_INDEX_PATH, dtype={"stock_code": "string", "rcept_no": "string"}, encoding="utf-8-sig")
seed_df = pd.read_csv(SEED_DICTIONARY_PATH, encoding="utf-8-sig")

for df in [company_master, filing_index]:
    df["stock_code"] = df["stock_code"].astype("string").str.zfill(6)

seed_df = seed_df.copy()
seed_df["dimension"] = seed_df["dimension"].astype(str).str.strip()
seed_df["seed_term"] = seed_df["seed_term"].astype(str).str.strip()
seed_df = seed_df[seed_df["dimension"].isin(["E", "S", "G"])].drop_duplicates(["dimension", "seed_term"])

print("company_master:", company_master.shape)
print("filing_index:", filing_index.shape)
print("seed_df:", seed_df.shape)
display(seed_df[["dimension", "seed_term", "pattern"]].head(20))
display(seed_df["dimension"].value_counts().rename_axis("dimension").reset_index(name="seed_count"))

company_master: (381, 13)
filing_index: (381, 13)
seed_df: (30, 6)

   dimension seed_term                 pattern
0          E        탄소                      탄소
1          E      온실가스                온실가스|GHG
2          E      탄소중립                    탄소중립
3          E       넷제로   넷제로|net zero|net-zero
4          E     재생에너지  재생에너지|renewable energy
5          E       에너지                     에너지
6          E        전력                전력|전력사용량
7          E       폐기물                     폐기물
8          E       재활용                재활용|자원순환
9          E        폐수               폐수|수질|물관리
10         S        안전                      안전
11         S      산업재해                산업재해|재해율
12         S      중대재해                    중대재해
13         S       임직원              임직원|직원|근로자
14         S        노동                   노동|노사
15         S        인권                      인권
16         S      교육훈련              교육훈련|교육|훈련
17         S       협력사                     협력사
18         S       공급망        공급망|supply chain
19         S      지역사회          지역사회|community

  dimension  seed_count
0         E          10
1         S          10
2         G          10

In [5]:
def normalize_text(text):
    text = "" if pd.isna(text) else str(text)
    text = unicodedata.normalize("NFKC", html.unescape(text))
    text = re.sub(r"<[^>]+>", " ", text)
    text = re.sub(r"https?://\S+|www\.\S+", " URL ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def normalize_term(term):
    return normalize_text(term)


def threshold_label(theta):
    return f"{theta:.2f}".replace(".", "_")


def dictionary_name(theta):
    return f"expanded_dictionary_theta_{threshold_label(theta)}"


def pattern_from_term(term):
    return re.escape(normalize_term(term))


def threshold_from_dictionary_path(path):
    match = re.fullmatch(r"expanded_dictionary_theta_(\d+)_(\d+)", path.stem)
    if match is None:
        raise ValueError(f"Cannot parse threshold from expanded dictionary filename: {path.name}")
    return float(f"{int(match.group(1))}.{match.group(2)}")

print("helpers ready")

helpers ready

In [6]:
def build_seed_dictionary_frame(seed_df):
    rows = []
    for _, row in seed_df.iterrows():
        values = [row.get("seed_term", "")]
        pattern = row.get("pattern", "")
        if pd.notna(pattern):
            values.extend(str(pattern).split("|"))
        seen = set()
        for value in values:
            term = normalize_term(value)
            if not term or term.lower() == "nan" or term in seen:
                continue
            seen.add(term)
            rows.append({
                "dictionary_name": "seed_dictionary",
                "threshold": np.nan,
                "dimension": row["dimension"],
                "seed_term": normalize_term(row["seed_term"]),
                "candidate_term": term,
                "pattern": pattern_from_term(term),
                "similarity": 1.0,
                "source": "seed",
                "seed_terms_matched": normalize_term(row["seed_term"]),
                "keep_review": True,
                "exclude_reason": "",
            })
    return pd.DataFrame(rows).drop_duplicates(["dimension", "candidate_term"]).reset_index(drop=True)


def load_seed_dictionary(seed_df):
    seed_dictionary_path = EXPANDED_OUTPUT_DIR / "seed_dictionary_normalized_for_comparison.csv"
    if seed_dictionary_path.exists():
        seed_dictionary = pd.read_csv(seed_dictionary_path, encoding="utf-8-sig")
        print("seed dictionary loaded:", seed_dictionary_path)
    else:
        seed_dictionary = build_seed_dictionary_frame(seed_df)
        seed_dictionary.to_csv(seed_dictionary_path, index=False, encoding="utf-8-sig")
        print("seed dictionary built from seed_df and saved:", seed_dictionary_path)
    return seed_dictionary


def discover_expanded_dictionary_files(requested_thresholds=None):
    files_by_threshold = {
        threshold_from_dictionary_path(path): path
        for path in sorted(EXPANDED_OUTPUT_DIR.glob("expanded_dictionary_theta_*.csv"))
    }
    if not files_by_threshold:
        raise FileNotFoundError(
            "No expanded dictionary CSVs found in "
            f"{EXPANDED_OUTPUT_DIR}. Run the new generation notebook first to create "
            "expanded_dictionary_theta_*.csv files."
        )

    if requested_thresholds is None:
        return files_by_threshold

    requested = [float(theta) for theta in requested_thresholds]
    missing = [theta for theta in requested if theta not in files_by_threshold]
    if missing:
        available = ", ".join(f"{theta:.2f}" for theta in sorted(files_by_threshold))
        missing_text = ", ".join(f"{theta:.2f}" for theta in missing)
        raise FileNotFoundError(
            f"Requested expanded dictionary thresholds not found: {missing_text}. "
            f"Available thresholds in {EXPANDED_OUTPUT_DIR}: {available}."
        )
    return {theta: files_by_threshold[theta] for theta in requested}


def load_expanded_dictionaries(requested_thresholds=None):
    files_by_threshold = discover_expanded_dictionary_files(requested_thresholds)
    dictionary_map = {}
    loaded_rows = []
    for theta, path in sorted(files_by_threshold.items()):
        df = pd.read_csv(path, encoding="utf-8-sig")
        name = dictionary_name(theta)
        dictionary_map[name] = df
        loaded_rows.append({
            "threshold": theta,
            "dictionary_name": name,
            "path": path,
            "rows": len(df),
        })
    return dictionary_map, pd.DataFrame(loaded_rows)


seed_dictionary_df = load_seed_dictionary(seed_df)
expanded_dictionary_map, expanded_dictionary_files_df = load_expanded_dictionaries(REQUESTED_THRESHOLDS)
THRESHOLDS = expanded_dictionary_files_df["threshold"].tolist()

print("discovered THRESHOLDS:", THRESHOLDS)
display(expanded_dictionary_files_df)

seed dictionary loaded: /content/drive/MyDrive/UD_26/final/expanded_dictionaries/seed_dictionary_normalized_for_comparison.csv
discovered THRESHOLDS: [0.55, 0.6, 0.65, 0.7, 0.8]

,threshold,dictionary_name,path,rows
0,0.55,expanded_dictionary_theta_0_55,/content/drive/MyDrive/UD_26/final/expanded_dictionaries/expanded_dictionary_theta_0_55.csv,2469
1,0.60,expanded_dictionary_theta_0_60,/content/drive/MyDrive/UD_26/final/expanded_dictionaries/expanded_dictionary_theta_0_60.csv,1158
2,0.65,expanded_dictionary_theta_0_65,/content/drive/MyDrive/UD_26/final/expanded_dictionaries/expanded_dictionary_theta_0_65.csv,408
3,0.70,expanded_dictionary_theta_0_70,/content/drive/MyDrive/UD_26/final/expanded_dictionaries/expanded_dictionary_theta_0_70.csv,100
4,0.80,expanded_dictionary_theta_0_80,/content/drive/MyDrive/UD_26/final/expanded_dictionaries/expanded_dictionary_theta_0_80.csv,53

In [7]:
def strip_tags_keep_space(xml_fragment):
    text = html.unescape(str(xml_fragment))
    text = re.sub(r"<[^>]+>", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return unicodedata.normalize("NFKC", text)


title_re = re.compile(r"<TITLE\b[^>]*>(.*?)</TITLE>", flags=re.I | re.S)
main_title_re = re.compile(r"^\s*(I|II|III|IV|V|VI|VII|VIII|IX|X|Ⅰ|Ⅱ|Ⅲ|Ⅳ|Ⅴ|Ⅵ|Ⅶ|Ⅷ|Ⅸ|Ⅹ)\.")
target_title_regex = {
    "II. 사업의 내용": r"^(II|Ⅱ)\.\s*사업의\s*내용",
    "IV. 이사의 경영진단 및 분석의견": r"^(IV|Ⅳ)\.\s*이사의\s*경영진단\s*및\s*분석의견",
    "VI. 이사회 등 회사의 기관에 관한 사항": r"^(VI|Ⅵ)\.\s*이사회\s*등\s*회사의\s*기관에\s*관한\s*사항",
}


def extract_target_sections(xml_text):
    matches = list(title_re.finditer(xml_text))
    sections = []
    active = None

    for i, match in enumerate(matches):
        title = strip_tags_keep_space(match.group(1))
        next_start = matches[i + 1].start() if i + 1 < len(matches) else len(xml_text)
        body = xml_text[match.end():next_start]

        if main_title_re.search(title):
            active = None
            for section_name, pattern in target_title_regex.items():
                if re.search(pattern, title):
                    active = section_name
                    break
            if active is None:
                continue

        if active:
            section_text = strip_tags_keep_space(body)
            if section_text:
                sections.append({"section": active, "title": title, "text": section_text})

    return sections

section_rows = []
missing_xml_rows = []

for _, row in filing_index.iterrows():
    xml_path_value = row.get("xml_path", "")
    xml_path_text = str(xml_path_value).replace("\\", "/")
    xml_path_candidates = [
        ROOT / xml_path_text,
        Path(xml_path_text),
        RAW_XML_DIR / Path(xml_path_text).name,
        FINAL_DIR / "raw_xml" / Path(xml_path_text).name,
        DART_DIR / "raw_xml" / Path(xml_path_text).name,
    ]
    xml_path = first_existing(xml_path_candidates, xml_path_candidates[0])
    if not xml_path.exists():
        missing_xml_rows.append({**row.to_dict(), "resolved_xml_path": str(xml_path)})
        continue

    xml_text = xml_path.read_text(encoding="utf-8", errors="ignore")
    for section in extract_target_sections(xml_text):
        section_rows.append({
            "stock_code": row["stock_code"],
            "company_name": row.get("company_name", ""),
            "fiscal_year": int(row["fiscal_year"]),
            "esg_year": int(row["esg_year"]),
            "rcept_no": row["rcept_no"],
            "section": section["section"],
            "section_text": normalize_text(section["text"]),
        })

section_df = pd.DataFrame(section_rows)
missing_xml_df = pd.DataFrame(missing_xml_rows)

print("section rows:", section_df.shape)
print("missing xml rows:", missing_xml_df.shape)
if not section_df.empty:
    display(section_df.groupby("section").size().rename("rows"))
    display(section_df.head())
else:
    raise ValueError("No target sections extracted. Check filing_index xml_path and section extraction rules.")

section rows: (4155, 7)
missing xml rows: (3, 14)

section
II. 사업의 내용                 2643
IV. 이사의 경영진단 및 분석의견         378
VI. 이사회 등 회사의 기관에 관한 사항    1134
Name: rows, dtype: int64

,stock_code,company_name,fiscal_year,esg_year,rcept_no,section,section_text
0,005930,삼성전자,2022,2022,20230307000542,II. 사업의 내용,"당사는 본사를 거점으로 한국과 DX 부문 산하 해외 9개 지역총괄 및 DS 부문 산하 해외 5개 지역총괄의 생산ᆞ판매법인, SDC 및 Harman 산하 종속기업 등 232개의 종속기업으로 구성된 글로벌 전자 기업입니다. 사업별로 보면, Set 사업은 TV를 비롯하여 모니터, 냉장..."
1,005930,삼성전자,2022,2022,20230307000542,II. 사업의 내용,"가. 주요 제품 매출 당사는 TV, 냉장고, 세탁기, 에어컨, HHP 등 완제품과 DRAM, NAND Flash, 모바일AP 등 반도체 부품 및 디스플레이 패널 등을 생산ᆞ판매하고 있습니다. 아울러 Harman을 통해 디지털 콕핏, 텔레매틱스 등을 생산ᆞ판매하고 있습니다.2022..."
2,005930,삼성전자,2022,2022,20230307000542,II. 사업의 내용,"가. 주요 원재료 현황 당사의 주요 원재료로 DX 부문은 모바일AP, Camera Module 등을 Qualcomm, 삼성전기(주) 등에서 공급받고 있으며, TVᆞ모니터용 디스플레이 패널 등을 CSOT 등으로부터 공급받고 있습니다. DS 부문은 Chemical, Wafer 등을 ..."
3,005930,삼성전자,2022,2022,20230307000542,II. 사업의 내용,"가. 매출실적 2022년 매출은 302조 2,314억원으로 전년 대비 8.1% 증가하였습니다. 부문별로 보면 전년 대비 DX 부문이 9.8%, DS 부문이 3.2% 증가하였으며, SDC가 8.4%, Harman이 31.6% 증가하였습니다. (단위 : 억원) 부 문 매출유형 품 목..."
4,005930,삼성전자,2022,2022,20230307000542,II. 사업의 내용,"가. 재무위험관리정책 당사의 재무위험관리는 영업 활동에서 파생되는 시장위험, 신용위험, 유동성위험 등을 최소화하는데 중점을 두고 있습니다. 당사는 이를 위해 각각의 위험요인에 대해 면밀하게 모니터링하고 대응하는 재무위험관리정책과 프로그램을 운영하고 있습니다. 위험을 회피하기 위한..."

In [8]:
corpus_df = (
    section_df.groupby(["stock_code", "company_name", "fiscal_year", "esg_year", "rcept_no"], as_index=False)
    .agg(
        document=("section_text", " ".join),
        section_count=("section", "nunique"),
    )
)
corpus_df["document_norm"] = corpus_df["document"].map(normalize_text)
corpus_df["total_char_count"] = corpus_df["document_norm"].str.len()
corpus_df["total_word_count"] = corpus_df["document_norm"].str.split().str.len()

print("firm-year corpus rows:", len(corpus_df))
display(corpus_df[["stock_code", "company_name", "fiscal_year", "esg_year", "section_count", "total_word_count"]].head())
display(corpus_df[["section_count", "total_word_count", "total_char_count"]].describe().T)

firm-year corpus rows: 378

,stock_code,company_name,fiscal_year,esg_year,section_count,total_word_count
0,000020,동화약품,2022,2022,3,7808
1,000020,동화약품,2023,2023,3,8065
2,000020,동화약품,2024,2024,3,8097
3,000040,KR모터스,2022,2022,3,4201
4,000040,KR모터스,2023,2023,3,4888

,count,mean,std,min,25%,50%,75%,max
section_count,378.0,3.000000,0.000000,3.0,3.0,3.0,3.00,3.0
total_word_count,378.0,14965.915344,12333.345076,1774.0,7611.5,11232.5,17153.75,71704.0
total_char_count,378.0,72960.116402,61337.067441,8657.0,36647.0,55039.5,83135.25,360632.0

In [9]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer


def prepare_dictionary_records(dictionary_df, label):
    usable = dictionary_df.copy()
    if "keep_review" in usable.columns:
        usable = usable[usable["keep_review"].astype(str).str.upper() != "FALSE"]
    usable = usable[usable["dimension"].isin(["E", "S", "G"])]
    usable["candidate_term"] = usable["candidate_term"].map(normalize_term)
    usable = usable[usable["candidate_term"].str.len() > 0]
    usable = usable.drop_duplicates(["dimension", "candidate_term"]).reset_index(drop=True)

    records = []
    for idx, row in usable.iterrows():
        term_id = f"{label}_{row['dimension']}_{idx:05d}"
        pattern = row.get("pattern", "")
        if pd.isna(pattern) or not str(pattern).strip():
            pattern = pattern_from_term(row["candidate_term"])
        records.append({
            "term_id": term_id,
            "dimension": row["dimension"],
            "candidate_term": row["candidate_term"],
            "source": row.get("source", ""),
            "similarity": row.get("similarity", np.nan),
            "regex": re.compile(str(pattern), flags=re.I),
        })
    return records


def score_dictionary(corpus_df, dictionary_df, label):
    records = prepare_dictionary_records(dictionary_df, label)
    if not records:
        raise ValueError(f"No usable dictionary terms for {label}")

    def dictionary_analyzer(text):
        text = normalize_text(text)
        tokens = []
        for rec in records:
            hit_count = len(rec["regex"].findall(text))
            if hit_count:
                tokens.extend([rec["term_id"]] * hit_count)
        return tokens

    count_vectorizer = CountVectorizer(analyzer=dictionary_analyzer, lowercase=False)
    X_count = count_vectorizer.fit_transform(corpus_df["document_norm"].fillna(""))
    feature_names = count_vectorizer.get_feature_names_out()

    presence_vectorizer = CountVectorizer(
        analyzer=dictionary_analyzer,
        lowercase=False,
        binary=True,
        vocabulary=count_vectorizer.vocabulary_,
    )
    X_presence = presence_vectorizer.transform(corpus_df["document_norm"].fillna(""))
    X_count_tfidf = TfidfTransformer(norm=None, use_idf=True, smooth_idf=True).fit_transform(X_count)
    X_presence_tfidf = TfidfTransformer(norm=None, use_idf=True, smooth_idf=True).fit_transform(X_presence)

    feature_df = pd.DataFrame({"term_id": feature_names})
    record_df = pd.DataFrame([{k: v for k, v in rec.items() if k != "regex"} for rec in records])
    feature_df = feature_df.merge(record_df, on="term_id", how="left")
    term_id_to_idx = {term_id: idx for idx, term_id in enumerate(feature_names)}

    out = corpus_df[["stock_code", "company_name", "fiscal_year", "esg_year", "rcept_no", "section_count", "total_word_count", "total_char_count"]].copy()
    word_denominator = out["total_word_count"].where(out["total_word_count"] != 0)

    dimensions = ["E", "S", "G"]
    for dimension in dimensions:
        term_ids = feature_df.loc[feature_df["dimension"] == dimension, "term_id"].tolist()
        cols = [term_id_to_idx[term_id] for term_id in term_ids if term_id in term_id_to_idx]
        if cols:
            out[f"{dimension}_{label}_count"] = X_count[:, cols].sum(axis=1).A1
            out[f"{dimension}_{label}_presence_count"] = X_presence[:, cols].sum(axis=1).A1
            out[f"{dimension}_{label}_count_tfidf_score"] = X_count_tfidf[:, cols].sum(axis=1).A1
            out[f"{dimension}_{label}_presence_tfidf_score"] = X_presence_tfidf[:, cols].sum(axis=1).A1
        else:
            out[f"{dimension}_{label}_count"] = 0.0
            out[f"{dimension}_{label}_presence_count"] = 0.0
            out[f"{dimension}_{label}_count_tfidf_score"] = 0.0
            out[f"{dimension}_{label}_presence_tfidf_score"] = 0.0
        out[f"{dimension}_{label}_share"] = out[f"{dimension}_{label}_count"] / word_denominator

    for metric in ["count", "presence_count", "count_tfidf_score", "presence_tfidf_score", "share"]:
        out[f"ESG_{label}_{metric}"] = sum(out[f"{dimension}_{label}_{metric}"] for dimension in dimensions)

    term_summary = feature_df.groupby(["dimension", "source"], dropna=False).size().rename("terms_observed").reset_index()
    hit_summary = []
    for dimension in dimensions:
        hit_summary.append({
            "dimension": dimension,
            "dictionary_label": label,
            "dictionary_terms": int(sum(1 for rec in records if rec["dimension"] == dimension)),
            "observed_terms": int((feature_df["dimension"] == dimension).sum()),
            "documents_with_any_hit": int((out[f"{dimension}_{label}_count"] > 0).sum()),
        })
    hit_summary = pd.DataFrame(hit_summary)

    return out, feature_df, term_summary, hit_summary

print("scoring function ready")

scoring function ready

In [10]:
from joblib import Parallel, delayed
import os


def score_one_dictionary(theta):
    label = f"expanded_{threshold_label(theta)}"
    name = dictionary_name(theta)
    score_df, feature_df, term_summary, hit_summary = score_dictionary(
        corpus_df,
        expanded_dictionary_map[name],
        label,
    )
    return theta, label, score_df, feature_df, term_summary, hit_summary


score_frames = []
term_summaries = []
hit_summaries = []
feature_maps = {}

seed_score_df, seed_feature_df, seed_term_summary, seed_hit_summary = score_dictionary(corpus_df, seed_dictionary_df, "seed")
score_frames.append(seed_score_df)
term_summaries.append(seed_term_summary.assign(dictionary_label="seed"))
hit_summaries.append(seed_hit_summary)
feature_maps["seed"] = seed_feature_df

# Colab notebooks are usually most stable with thread-based parallelism.
# Increase n_jobs cautiously if the runtime has enough CPU and memory.
n_jobs = min(4, os.cpu_count() or 1)
print(f"Scoring {len(THRESHOLDS)} expanded dictionaries with n_jobs={n_jobs}")

results = Parallel(n_jobs=n_jobs, prefer="threads", verbose=10)(
    delayed(score_one_dictionary)(theta)
    for theta in THRESHOLDS
)

for theta, label, score_df, feature_df, term_summary, hit_summary in results:
    score_frames.append(score_df)
    term_summaries.append(term_summary.assign(dictionary_label=label, threshold=theta))
    hit_summaries.append(hit_summary.assign(threshold=theta))
    feature_maps[label] = feature_df

base_cols = ["stock_code", "company_name", "fiscal_year", "esg_year", "rcept_no", "section_count", "total_word_count", "total_char_count"]
all_score_df = score_frames[0]
for frame in score_frames[1:]:
    metric_cols = [col for col in frame.columns if col not in base_cols]
    all_score_df = all_score_df.merge(frame[base_cols[:5] + metric_cols], on=base_cols[:5], how="left")

term_summary_df = pd.concat(term_summaries, ignore_index=True)
hit_summary_df = pd.concat(hit_summaries, ignore_index=True)

print("all_score_df:", all_score_df.shape)
display(hit_summary_df)
display(all_score_df.head())

Scoring 5 expanded dictionaries with n_jobs=2

[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   1 tasks      | elapsed:  9.9min
[Parallel(n_jobs=2)]: Done   3 out of   5 | elapsed: 14.4min remaining:  9.6min

all_score_df: (378, 128)

[Parallel(n_jobs=2)]: Done   5 out of   5 | elapsed: 19.1min finished

,dimension,dictionary_label,dictionary_terms,observed_terms,documents_with_any_hit,threshold
0,E,seed,18,18,304,NaN
1,S,seed,18,18,378,NaN
2,G,seed,17,15,378,NaN
3,E,expanded_0_55,954,152,329,0.55
4,S,expanded_0_55,830,148,378,0.55
5,G,expanded_0_55,685,93,378,0.55
6,E,expanded_0_60,806,67,307,0.60
7,S,expanded_0_60,204,62,378,0.60
8,G,expanded_0_60,148,56,378,0.60
9,E,expanded_0_65,307,44,304,0.65
10,S,expanded_0_65,46,28,378,0.65
11,G,expanded_0_65,55,39,378,0.65
12,E,expanded_0_70,41,31,304,0.70
13,S,expanded_0_70,25,19,378,0.70
14,G,expanded_0_70,34,26,378,0.70
15,E,expanded_0_80,18,18,304,0.80
16,S,expanded_0_80,18,18,378,0.80
17,G,expanded_0_80,17,15,378,0.80

,stock_code,company_name,fiscal_year,esg_year,rcept_no,section_count,total_word_count,total_char_count,E_seed_count,E_seed_presence_count,...,G_expanded_0_80_count,G_expanded_0_80_presence_count,G_expanded_0_80_count_tfidf_score,G_expanded_0_80_presence_tfidf_score,G_expanded_0_80_share,ESG_expanded_0_80_count,ESG_expanded_0_80_presence_count,ESG_expanded_0_80_count_tfidf_score,ESG_expanded_0_80_presence_tfidf_score,ESG_expanded_0_80_share
0,000020,동화약품,2022,2022,20230315001100,3,7808,37953,0,0,...,100,10,109.180137,14.362805,0.012807,117,14,127.288133,19.351628,0.014985
1,000020,동화약품,2023,2023,20240319000652,3,8065,38467,0,0,...,97,10,103.951513,14.362805,0.012027,113,13,120.184567,17.476687,0.014011
2,000020,동화약품,2024,2024,20250318000739,3,8097,39259,0,0,...,97,10,103.876235,14.362805,0.011980,114,14,121.984231,19.351628,0.014079
3,000040,KR모터스,2022,2022,20230322001182,3,4201,20136,1,1,...,22,6,22.064378,6.064378,0.005237,38,10,39.482257,10.934013,0.009045
4,000040,KR모터스,2023,2023,20240321002062,3,4888,22402,2,2,...,19,6,19.064378,6.064378,0.003887,38,11,40.183446,12.314721,0.007774

In [11]:
def normalize_stock_code(series):
    return (
        series.astype("string")
        .str.strip()
        .str.replace(r"\.0$", "", regex=True)
        .str.extract(r"(\d+)", expand=False)
        .str.zfill(6)
    )


grade_cols = ["stock_code", "fiscal_year", "industry", "esg_year", "esg_grade", "e_grade", "s_grade", "g_grade"]
grade_df = company_master[grade_cols].copy()
grade_df["stock_code"] = normalize_stock_code(grade_df["stock_code"])
all_score_df["stock_code"] = normalize_stock_code(all_score_df["stock_code"])
for col in ["fiscal_year", "esg_year"]:
    grade_df[col] = pd.to_numeric(grade_df[col], errors="coerce").astype("Int64")
    all_score_df[col] = pd.to_numeric(all_score_df[col], errors="coerce").astype("Int64")
all_score_df["esg_year"] = all_score_df["fiscal_year"] + 1
for col in ["esg_grade", "e_grade", "s_grade", "g_grade"]:
    grade_df[f"{col}_num"] = grade_df[col].map(GRADE_MAP)

score_keys = all_score_df[["stock_code", "fiscal_year", "esg_year"]].drop_duplicates()
grade_keys = grade_df[["stock_code", "fiscal_year", "esg_year"]].drop_duplicates()
matched_keys = score_keys.merge(grade_keys, on=["stock_code", "fiscal_year", "esg_year"], how="inner")
print("score key rows:", len(score_keys))
print("grade key rows:", len(grade_keys))
print("matched key rows:", len(matched_keys))
if matched_keys.empty:
    print("Sample score keys:")
    display(score_keys.head(10))
    print("Sample grade keys:")
    display(grade_keys.head(10))

analysis_df = all_score_df.merge(grade_df, on=["stock_code", "fiscal_year", "esg_year"], how="left")
missing_grade_mask = analysis_df["esg_grade_num"].isna()

print("analysis rows:", len(analysis_df))
print("missing esg_grade_num:", missing_grade_mask.sum())
if missing_grade_mask.any():
    print("Sample unmatched merge keys:")
    display(analysis_df.loc[missing_grade_mask, ["stock_code", "fiscal_year", "esg_year"]].drop_duplicates().head(10))
display(analysis_df[["company_name", "stock_code", "fiscal_year", "esg_grade", "esg_grade_num", "total_word_count", "ESG_seed_count", "ESG_seed_count_tfidf_score", "ESG_seed_presence_tfidf_score"]].head())

score key rows: 378
grade key rows: 381
matched key rows: 378
analysis rows: 378
missing esg_grade_num: 0

,company_name,stock_code,fiscal_year,esg_grade,esg_grade_num,total_word_count,ESG_seed_count,ESG_seed_count_tfidf_score,ESG_seed_presence_tfidf_score
0,동화약품,000020,2022,C,1,7808,117,127.288133,19.351628
1,동화약품,000020,2023,C,1,8065,113,120.184567,17.476687
2,동화약품,000020,2024,C,1,8097,114,121.984231,19.351628
3,KR모터스,000040,2022,D,0,4201,38,39.482257,10.934013
4,KR모터스,000040,2023,D,0,4888,38,40.183446,12.314721

In [12]:
from scipy.stats import spearmanr


def spearman_for_feature(data, y_col, x_col):
    tmp = data[[y_col, x_col]].replace([np.inf, -np.inf], np.nan).dropna()
    if len(tmp) < 3 or tmp[x_col].nunique() < 2 or tmp[y_col].nunique() < 2:
        return len(tmp), np.nan, np.nan
    rho, p_value = spearmanr(tmp[x_col], tmp[y_col])
    return len(tmp), float(rho), float(p_value)

metric_suffixes = ["count", "presence_count", "count_tfidf_score", "presence_tfidf_score", "share"]
dictionary_labels = ["seed"] + [f"expanded_{threshold_label(theta)}" for theta in THRESHOLDS]

spearman_rows = []
for label in dictionary_labels:
    theta = np.nan if label == "seed" else float(label.split("_")[-2] + "." + label.split("_")[-1])
    for dimension, y_col in [("ESG", "esg_grade_num"), ("E", "e_grade_num"), ("S", "s_grade_num"), ("G", "g_grade_num")]:
        for metric in metric_suffixes:
            x_col = f"{dimension}_{label}_{metric}"
            if x_col not in analysis_df.columns:
                continue
            n, rho, p_value = spearman_for_feature(analysis_df, y_col, x_col)
            spearman_rows.append({
                "dictionary_label": label,
                "threshold": theta,
                "dimension": dimension,
                "grade_col": y_col,
                "metric": metric,
                "feature": x_col,
                "n": n,
                "spearman_rho": rho,
                "p_value": p_value,
            })

spearman_comparison_df = pd.DataFrame(spearman_rows).sort_values(["dimension", "metric", "spearman_rho"], ascending=[True, True, False])
display(spearman_comparison_df)

main_spearman_df = spearman_comparison_df[
    (spearman_comparison_df["dimension"] == "ESG")
    & (spearman_comparison_df["metric"].isin(["count", "presence_count", "count_tfidf_score", "presence_tfidf_score"]))
].sort_values(["metric", "spearman_rho"], ascending=[True, False])

display(main_spearman_df)

,dictionary_label,threshold,dimension,grade_col,metric,feature,n,spearman_rho,p_value
25,expanded_0_55,0.55,E,e_grade_num,count,E_expanded_0_55_count,378,0.530893,7.160677e-29
65,expanded_0_65,0.65,E,e_grade_num,count,E_expanded_0_65_count,378,0.529405,1.084587e-28
5,seed,NaN,E,e_grade_num,count,E_seed_count,378,0.527976,1.613315e-28
105,expanded_0_80,0.80,E,e_grade_num,count,E_expanded_0_80_count,378,0.527976,1.613315e-28
85,expanded_0_70,0.70,E,e_grade_num,count,E_expanded_0_70_count,378,0.526468,2.447531e-28
45,expanded_0_60,0.60,E,e_grade_num,count,E_expanded_0_60_count,378,0.522233,7.803565e-28
7,seed,NaN,E,e_grade_num,count_tfidf_score,E_seed_count_tfidf_score,378,0.535904,1.741530e-29
107,expanded_0_80,0.80,E,e_grade_num,count_tfidf_score,E_expanded_0_80_count_tfidf_score,378,0.535904,1.741530e-29
67,expanded_0_65,0.65,E,e_grade_num,count_tfidf_score,E_expanded_0_65_count_tfidf_score,378,0.534420,2.653672e-29
87,expanded_0_70,0.70,E,e_grade_num,count_tfidf_score,E_expanded_0_70_count_tfidf_score,378,0.531807,5.541553e-29
27,expanded_0_55,0.55,E,e_grade_num,count_tfidf_score,E_expanded_0_55_count_tfidf_score,378,0.528749,1.301764e-28
47,expanded_0_60,0.60,E,e_grade_num,count_tfidf_score,E_expanded_0_60_count_tfidf_score,378,0.524069,4.729179e-28
46,expanded_0_60,0.60,E,e_grade_num,presence_count,E_expanded_0_60_presence_count,378,0.514968,5.493853e-27
26,expanded_0_55,0.55,E,e_grade_num,presence_count,E_expanded_0_55_presence_count,378,0.510250,1.903077e-26
66,expanded_0_65,0.65,E,e_grade_num,presence_count,E_expanded_0_65_presence_count,378,0.509809,2.135371e-26
6,seed,NaN,E,e_grade_num,presence_count,E_seed_presence_count,378,0.505546,6.443491e-26
106,expanded_0_80,0.80,E,e_grade_num,presence_count,E_expanded_0_80_presence_count,378,0.505546,6.443491e-26
86,expanded_0_70,0.70,E,e_grade_num,presence_count,E_expanded_0_70_presence_count,378,0.501020,2.047174e-25
48,expanded_0_60,0.60,E,e_grade_num,presence_tfidf_score,E_expanded_0_60_presence_tfidf_score,378,0.520603,1.213952e-27
8,seed,NaN,E,e_grade_num,presence_tfidf_score,E_seed_presence_tfidf_score,378,0.516349,3.804253e-27
108,expanded_0_80,0.80,E,e_grade_num,presence_tfidf_score,E_expanded_0_80_presence_tfidf_score,378,0.516349,3.804253e-27
68,expanded_0_65,0.65,E,e_grade_num,presence_tfidf_score,E_expanded_0_65_presence_tfidf_score,378,0.514422,6.349217e-27
88,expanded_0_70,0.70,E,e_grade_num,presence_tfidf_score,E_expanded_0_70_presence_tfidf_score,378,0.509666,2.216195e-26
28,expanded_0_55,0.55,E,e_grade_num,presence_tfidf_score,E_expanded_0_55_presence_tfidf_score,378,0.509597,2.256617e-26
69,expanded_0_65,0.65,E,e_grade_num,share,E_expanded_0_65_share,378,0.404276,2.699313e-16
9,seed,NaN,E,e_grade_num,share,E_seed_share,378,0.401035,4.886033e-16
109,expanded_0_80,0.80,E,e_grade_num,share,E_expanded_0_80_share,378,0.401035,4.886033e-16
89,expanded_0_70,0.70,E,e_grade_num,share,E_expanded_0_70_share,378,0.400143,5.746183e-16
29,expanded_0_55,0.55,E,e_grade_num,share,E_expanded_0_55_share,378,0.396726,1.064751e-15
49,expanded_0_60,0.60,E,e_grade_num,share,E_expanded_0_60_share,378,0.393048,2.052046e-15
0,seed,NaN,ESG,esg_grade_num,count,ESG_seed_count,378,0.719860,1.364310e-61
100,expanded_0_80,0.80,ESG,esg_grade_num,count,ESG_expanded_0_80_count,378,0.719860,1.364310e-61
80,expanded_0_70,0.70,ESG,esg_grade_num,count,ESG_expanded_0_70_count,378,0.714937,2.119527e-60
20,expanded_0_55,0.55,ESG,esg_grade_num,count,ESG_expanded_0_55_count,378,0.705889,2.825300e-58
60,expanded_0_65,0.65,ESG,esg_grade_num,count,ESG_expanded_0_65_count,378,0.703765,8.671543e-58
40,expanded_0_60,0.60,ESG,esg_grade_num,count,ESG_expanded_0_60_count,378,0.701950,2.242954e-57
2,seed,NaN,ESG,esg_grade_num,count_tfidf_score,ESG_seed_count_tfidf_score,378,0.719589,1.589053e-61
102,expanded_0_80,0.80,ESG,esg_grade_num,count_tfidf_score,ESG_expanded_0_80_count_tfidf_score,378,0.719589,1.589053e-61
82,expanded_0_70,0.70,ESG,esg_grade_num,count_tfidf_score,ESG_expanded_0_70_count_tfidf_score,378,0.712336,8.822280e-60
22,expanded_0_55,0.55,ESG,esg_grade_num,count_tfidf_score,ESG_expanded_0_55_count_tfidf_score,378,0.707984,9.252479e-59
62,expanded_0_65,0.65,ESG,esg_grade_num,count_tfidf_score,ESG_expanded_0_65_count_tfidf_score,378,0.702803,1.436595e-57
42,expanded_0_60,0.60,ESG,esg_grade_num,count_tfidf_score,ESG_expanded_0_60_count_tfidf_score,378,0.702223,1.945107e-57
41,expanded_0_60,0.60,ESG,esg_grade_num,presence_count,ESG_expanded_0_60_presence_count,378,0.650867,6.475150e-47
21,expanded_0_55,0.55,ESG,esg_grade_num,presence_count,ESG_expanded_0_55_presence_count,378,0.643900,1.212901e-45
61,expanded_0_65,0.65,ESG,esg_grade_num,presence_count,ESG_expanded_0_65_presence_count,378,0.641396,3.411819e-45
81,expanded_0_70,0.70,ESG,esg_grade_num,presence_count,ESG_expanded_0_70_presence_count,378,0.639017,9.038390e-45
1,seed,NaN,ESG,esg_grade_num,presence_count,ESG_seed_presence_count,378,0.605798,3.125205e-39
101,expanded_0_80,0.80,ESG,esg_grade_num,presence_count,ESG_expanded_0_80_presence_count,378,0.605798,3.125205e-39
43,expanded_0_60,0.60,ESG,esg_grade_num,presence_tfidf_score,ESG_expanded_0_60_presence_tfidf_score,378,0.628180,6.868036e-43
23,expanded_0_55,0.55,ESG,esg_grade_num,presence_tfidf_score,ESG_expanded_0_55_presence_tfidf_score,378,0.625085,2.292938e-42
63,expanded_0_65,0.65,ESG,esg_grade_num,presence_tfidf_score,ESG_expanded_0_65_presence_tfidf_score,378,0.622006,7.506366e-42
83,expanded_0_70,0.70,ESG,esg_grade_num,presence_tfidf_score,ESG_expanded_0_70_presence_tfidf_score,378,0.618054,3.375193e-41
3,seed,NaN,ESG,esg_grade_num,presence_tfidf_score,ESG_seed_presence_tfidf_score,378,0.602705,9.498032e-39
103,expanded_0_80,0.80,ESG,esg_grade_num,presence_tfidf_score,ESG_expanded_0_80_presence_tfidf_score,378,0.602705,9.498032e-39
64,expanded_0_65,0.65,ESG,esg_grade_num,share,ESG_expanded_0_65_share,378,0.046866,3.635309e-01
24,expanded_0_55,0.55,ESG,esg_grade_num,share,ESG_expanded_0_55_share,378,0.043700,3.968752e-01
84,expanded_0_70,0.70,ESG,esg_grade_num,share,ESG_expanded_0_70_share,378,0.042364,4.114816e-01
44,expanded_0_60,0.60,ESG,esg_grade_num,share,ESG_expanded_0_60_share,378,0.033446,5.167917e-01
4,seed,NaN,ESG,esg_grade_num,share,ESG_seed_share,378,0.032721,5.259251e-01
104,expanded_0_80,0.80,ESG,esg_grade_num,share,ESG_expanded_0_80_share,378,0.032721,5.259251e-01
15,seed,NaN,G,g_grade_num,count,G_seed_count,378,0.625622,1.861979e-42
115,expanded_0_80,0.80,G,g_grade_num,count,G_expanded_0_80_count,378,0.625622,1.861979e-42
95,expanded_0_70,0.70,G,g_grade_num,count,G_expanded_0_70_count,378,0.622527,6.147776e-42
75,expanded_0_65,0.65,G,g_grade_num,count,G_expanded_0_65_count,378,0.609419,8.369502e-40
35,expanded_0_55,0.55,G,g_grade_num,count,G_expanded_0_55_count,378,0.604571,4.863212e-39
55,expanded_0_60,0.60,G,g_grade_num,count,G_expanded_0_60_count,378,0.602722,9.440915e-39
17,seed,NaN,G,g_grade_num,count_tfidf_score,G_seed_count_tfidf_score,378,0.637397,1.746250e-44
117,expanded_0_80,0.80,G,g_grade_num,count_tfidf_score,G_expanded_0_80_count_tfidf_score,378,0.637397,1.746250e-44
97,expanded_0_70,0.70,G,g_grade_num,count_tfidf_score,G_expanded_0_70_count_tfidf_score,378,0.632143,1.438173e-43
77,expanded_0_65,0.65,G,g_grade_num,count_tfidf_score,G_expanded_0_65_count_tfidf_score,378,0.618019,3.419920e-41
37,expanded_0_55,0.55,G,g_grade_num,count_tfidf_score,G_expanded_0_55_count_tfidf_score,378,0.616801,5.410231e-41
57,expanded_0_60,0.60,G,g_grade_num,count_tfidf_score,G_expanded_0_60_count_tfidf_score,378,0.612319,2.878102e-40
96,expanded_0_70,0.70,G,g_grade_num,presence_count,G_expanded_0_70_presence_count,378,0.596624,8.162635e-38
36,expanded_0_55,0.55,G,g_grade_num,presence_count,G_expanded_0_55_presence_count,378,0.593705,2.255812e-37
76,expanded_0_65,0.65,G,g_grade_num,presence_count,G_expanded_0_65_presence_count,378,0.577900,4.644578e-35
56,expanded_0_60,0.60,G,g_grade_num,presence_count,G_expanded_0_60_presence_count,378,0.575947,8.793146e-35
16,seed,NaN,G,g_grade_num,presence_count,G_seed_presence_count,378,0.559559,1.581296e-32
116,expanded_0_80,0.80,G,g_grade_num,presence_count,G_expanded_0_80_presence_count,378,0.559559,1.581296e-32
38,expanded_0_55,0.55,G,g_grade_num,presence_tfidf_score,G_expanded_0_55_presence_tfidf_score,378,0.589897,8.364205e-37
98,expanded_0_70,0.70,G,g_grade_num,presence_tfidf_score,G_expanded_0_70_presence_tfidf_score,378,0.575250,1.103132e-34
78,expanded_0_65,0.65,G,g_grade_num,presence_tfidf_score,G_expanded_0_65_presence_tfidf_score,378,0.564077,3.888584e-33
58,expanded_0_60,0.60,G,g_grade_num,presence_tfidf_score,G_expanded_0_60_presence_tfidf_score,378,0.560029,1.367642e-32
18,seed,NaN,G,g_grade_num,presence_tfidf_score,G_seed_presence_tfidf_score,378,0.553438,1.022009e-31
118,expanded_0_80,0.80,G,g_grade_num,presence_tfidf_score,G_expanded_0_80_presence_tfidf_score,378,0.553438,1.022009e-31
79,expanded_0_65,0.65,G,g_grade_num,share,G_expanded_0_65_share,378,-0.079409,1.232654e-01
59,expanded_0_60,0.60,G,g_grade_num,share,G_expanded_0_60_share,378,-0.091037,7.709802e-02
39,expanded_0_55,0.55,G,g_grade_num,share,G_expanded_0_55_share,378,-0.096857,5.992949e-02
99,expanded_0_70,0.70,G,g_grade_num,share,G_expanded_0_70_share,378,-0.108778,3.450136e-02
19,seed,NaN,G,g_grade_num,share,G_seed_share,378,-0.124264,1.563432e-02
119,expanded_0_80,0.80,G,g_grade_num,share,G_expanded_0_80_share,378,-0.124264,1.563432e-02
30,expanded_0_55,0.55,S,s_grade_num,count,S_expanded_0_55_count,378,0.625194,2.198459e-42
50,expanded_0_60,0.60,S,s_grade_num,count,S_expanded_0_60_count,378,0.618738,2.606108e-41
90,expanded_0_70,0.70,S,s_grade_num,count,S_expanded_0_70_count,378,0.618575,2.771674e-41
10,seed,NaN,S,s_grade_num,count,S_seed_count,378,0.618567,2.779576e-41
110,expanded_0_80,0.80,S,s_grade_num,count,S_expanded_0_80_count,378,0.618567,2.779576e-41
70,expanded_0_65,0.65,S,s_grade_num,count,S_expanded_0_65_count,378,0.617965,3.489580e-41
12,seed,NaN,S,s_grade_num,count_tfidf_score,S_seed_count_tfidf_score,378,0.616054,7.162684e-41
112,expanded_0_80,0.80,S,s_grade_num,count_tfidf_score,S_expanded_0_80_count_tfidf_score,378,0.616054,7.162684e-41
92,expanded_0_70,0.70,S,s_grade_num,count_tfidf_score,S_expanded_0_70_count_tfidf_score,378,0.616015,7.267394e-41
72,expanded_0_65,0.65,S,s_grade_num,count_tfidf_score,S_expanded_0_65_count_tfidf_score,378,0.613701,1.724471e-40
52,expanded_0_60,0.60,S,s_grade_num,count_tfidf_score,S_expanded_0_60_count_tfidf_score,378,0.605863,3.051996e-39
32,expanded_0_55,0.55,S,s_grade_num,count_tfidf_score,S_expanded_0_55_count_tfidf_score,378,0.603235,7.858566e-39
31,expanded_0_55,0.55,S,s_grade_num,presence_count,S_expanded_0_55_presence_count,378,0.548101,5.041707e-31
91,expanded_0_70,0.70,S,s_grade_num,presence_count,S_expanded_0_70_presence_count,378,0.509348,2.408189e-26
11,seed,NaN,S,s_grade_num,presence_count,S_seed_presence_count,378,0.508962,2.662535e-26
111,expanded_0_80,0.80,S,s_grade_num,presence_count,S_expanded_0_80_presence_count,378,0.508962,2.662535e-26
71,expanded_0_65,0.65,S,s_grade_num,presence_count,S_expanded_0_65_presence_count,378,0.504482,8.468652e-26
51,expanded_0_60,0.60,S,s_grade_num,presence_count,S_expanded_0_60_presence_count,378,0.502991,1.240011e-25
33,expanded_0_55,0.55,S,s_grade_num,presence_tfidf_score,S_expanded_0_55_presence_tfidf_score,378,0.526577,2.374626e-28
13,seed,NaN,S,s_grade_num,presence_tfidf_score,S_seed_presence_tfidf_score,378,0.485974,8.455385e-24
113,expanded_0_80,0.80,S,s_grade_num,presence_tfidf_score,S_expanded_0_80_presence_tfidf_score,378,0.485974,8.455385e-24
93,expanded_0_70,0.70,S,s_grade_num,presence_tfidf_score,S_expanded_0_70_presence_tfidf_score,378,0.485906,8.594282e-24
53,expanded_0_60,0.60,S,s_grade_num,presence_tfidf_score,S_expanded_0_60_presence_tfidf_score,378,0.477645,6.136565e-23
73,expanded_0_65,0.65,S,s_grade_num,presence_tfidf_score,S_expanded_0_65_presence_tfidf_score,378,0.476577,7.880908e-23
34,expanded_0_55,0.55,S,s_grade_num,share,S_expanded_0_55_share,378,0.146100,4.421820e-03
54,expanded_0_60,0.60,S,s_grade_num,share,S_expanded_0_60_share,378,0.143863,5.073212e-03
74,expanded_0_65,0.65,S,s_grade_num,share,S_expanded_0_65_share,378,0.132640,9.831919e-03
94,expanded_0_70,0.70,S,s_grade_num,share,S_expanded_0_70_share,378,0.127524,1.309092e-02
14,seed,NaN,S,s_grade_num,share,S_seed_share,378,0.127256,1.328528e-02
114,expanded_0_80,0.80,S,s_grade_num,share,S_expanded_0_80_share,378,0.127256,1.328528e-02

,dictionary_label,threshold,dimension,grade_col,metric,feature,n,spearman_rho,p_value
0,seed,NaN,ESG,esg_grade_num,count,ESG_seed_count,378,0.719860,1.364310e-61
100,expanded_0_80,0.80,ESG,esg_grade_num,count,ESG_expanded_0_80_count,378,0.719860,1.364310e-61
80,expanded_0_70,0.70,ESG,esg_grade_num,count,ESG_expanded_0_70_count,378,0.714937,2.119527e-60
20,expanded_0_55,0.55,ESG,esg_grade_num,count,ESG_expanded_0_55_count,378,0.705889,2.825300e-58
60,expanded_0_65,0.65,ESG,esg_grade_num,count,ESG_expanded_0_65_count,378,0.703765,8.671543e-58
40,expanded_0_60,0.60,ESG,esg_grade_num,count,ESG_expanded_0_60_count,378,0.701950,2.242954e-57
2,seed,NaN,ESG,esg_grade_num,count_tfidf_score,ESG_seed_count_tfidf_score,378,0.719589,1.589053e-61
102,expanded_0_80,0.80,ESG,esg_grade_num,count_tfidf_score,ESG_expanded_0_80_count_tfidf_score,378,0.719589,1.589053e-61
82,expanded_0_70,0.70,ESG,esg_grade_num,count_tfidf_score,ESG_expanded_0_70_count_tfidf_score,378,0.712336,8.822280e-60
22,expanded_0_55,0.55,ESG,esg_grade_num,count_tfidf_score,ESG_expanded_0_55_count_tfidf_score,378,0.707984,9.252479e-59
62,expanded_0_65,0.65,ESG,esg_grade_num,count_tfidf_score,ESG_expanded_0_65_count_tfidf_score,378,0.702803,1.436595e-57
42,expanded_0_60,0.60,ESG,esg_grade_num,count_tfidf_score,ESG_expanded_0_60_count_tfidf_score,378,0.702223,1.945107e-57
41,expanded_0_60,0.60,ESG,esg_grade_num,presence_count,ESG_expanded_0_60_presence_count,378,0.650867,6.475150e-47
21,expanded_0_55,0.55,ESG,esg_grade_num,presence_count,ESG_expanded_0_55_presence_count,378,0.643900,1.212901e-45
61,expanded_0_65,0.65,ESG,esg_grade_num,presence_count,ESG_expanded_0_65_presence_count,378,0.641396,3.411819e-45
81,expanded_0_70,0.70,ESG,esg_grade_num,presence_count,ESG_expanded_0_70_presence_count,378,0.639017,9.038390e-45
1,seed,NaN,ESG,esg_grade_num,presence_count,ESG_seed_presence_count,378,0.605798,3.125205e-39
101,expanded_0_80,0.80,ESG,esg_grade_num,presence_count,ESG_expanded_0_80_presence_count,378,0.605798,3.125205e-39
43,expanded_0_60,0.60,ESG,esg_grade_num,presence_tfidf_score,ESG_expanded_0_60_presence_tfidf_score,378,0.628180,6.868036e-43
23,expanded_0_55,0.55,ESG,esg_grade_num,presence_tfidf_score,ESG_expanded_0_55_presence_tfidf_score,378,0.625085,2.292938e-42
63,expanded_0_65,0.65,ESG,esg_grade_num,presence_tfidf_score,ESG_expanded_0_65_presence_tfidf_score,378,0.622006,7.506366e-42
83,expanded_0_70,0.70,ESG,esg_grade_num,presence_tfidf_score,ESG_expanded_0_70_presence_tfidf_score,378,0.618054,3.375193e-41
3,seed,NaN,ESG,esg_grade_num,presence_tfidf_score,ESG_seed_presence_tfidf_score,378,0.602705,9.498032e-39
103,expanded_0_80,0.80,ESG,esg_grade_num,presence_tfidf_score,ESG_expanded_0_80_presence_tfidf_score,378,0.602705,9.498032e-39

In [13]:
import statsmodels.api as sm


def zscore(series):
    series = series.astype(float)
    std = series.std(ddof=0)
    if std == 0 or pd.isna(std):
        return series * 0
    return (series - series.mean()) / std


def run_ols(data, y_col, x_cols, min_n=3):
    required_cols = [y_col] + x_cols
    missing_cols = [col for col in required_cols if col not in data.columns]
    if missing_cols:
        return None, {"skip_reason": f"missing columns: {missing_cols}", "n": 0}

    reg_df = data[required_cols].replace([np.inf, -np.inf], np.nan).dropna().copy()
    if len(reg_df) < min_n:
        return None, {
            "skip_reason": f"too few complete rows after dropna: {len(reg_df)}",
            "n": int(len(reg_df)),
            "missing_by_col": data[required_cols].isna().sum().to_dict(),
        }

    y = reg_df[y_col].astype(float)
    X = reg_df[x_cols].apply(zscore)
    X = sm.add_constant(X, has_constant="add")
    model = sm.OLS(y, X).fit(cov_type="HC3")
    return model, {"skip_reason": "", "n": int(model.nobs)}

ols_rows = []
ols_skip_rows = []
for label in dictionary_labels:
    theta = np.nan if label == "seed" else float(label.split("_")[-2] + "." + label.split("_")[-1])
    for metric in ["count", "presence_count", "count_tfidf_score", "presence_tfidf_score"]:
        x_col = f"ESG_{label}_{metric}"
        if x_col not in analysis_df.columns:
            continue
        model, ols_info = run_ols(analysis_df, "esg_grade_num", [x_col, "total_word_count"])
        if model is None:
            ols_skip_rows.append({
                "dictionary_label": label,
                "threshold": theta,
                "metric": metric,
                "feature": x_col,
                **ols_info,
            })
            continue
        ols_rows.append({
            "dictionary_label": label,
            "threshold": theta,
            "metric": metric,
            "feature": x_col,
            "n": int(model.nobs),
            "coef": float(model.params[x_col]),
            "std_err": float(model.bse[x_col]),
            "p_value": float(model.pvalues[x_col]),
            "r2": float(model.rsquared),
            "word_count_coef": float(model.params["total_word_count"]),
            "word_count_p_value": float(model.pvalues["total_word_count"]),
        })

ols_comparison_df = pd.DataFrame(ols_rows)
if not ols_comparison_df.empty:
    ols_comparison_df = ols_comparison_df.sort_values(["metric", "r2"], ascending=[True, False])
display(ols_comparison_df)

ols_skip_df = pd.DataFrame(ols_skip_rows)
if not ols_skip_df.empty:
    print("Skipped OLS models:", len(ols_skip_df))
    display(ols_skip_df)

,dictionary_label,threshold,metric,feature,n,coef,std_err,p_value,r2,word_count_coef,word_count_p_value
8,expanded_0_60,0.60,count,ESG_expanded_0_60_count,378,1.006010,0.117103,8.634836e-18,0.382686,-0.011815,0.904065
12,expanded_0_65,0.65,count,ESG_expanded_0_65_count,378,1.024020,0.126535,5.833080e-16,0.380763,-0.037394,0.713712
4,expanded_0_55,0.55,count,ESG_expanded_0_55_count,378,1.044272,0.124661,5.434185e-17,0.375359,-0.070611,0.497158
16,expanded_0_70,0.70,count,ESG_expanded_0_70_count,378,0.970092,0.147319,4.549075e-11,0.362589,0.000041,0.999682
0,seed,NaN,count,ESG_seed_count,378,0.963747,0.155308,5.456405e-10,0.360978,0.005193,0.959958
20,expanded_0_80,0.80,count,ESG_expanded_0_80_count,378,0.963747,0.155308,5.456405e-10,0.360978,0.005193,0.959958
10,expanded_0_60,0.60,count_tfidf_score,ESG_expanded_0_60_count_tfidf_score,378,0.819726,0.130488,3.341963e-10,0.333053,0.133539,0.150758
14,expanded_0_65,0.65,count_tfidf_score,ESG_expanded_0_65_count_tfidf_score,378,0.826557,0.142989,7.445022e-09,0.332237,0.123401,0.200644
6,expanded_0_55,0.55,count_tfidf_score,ESG_expanded_0_55_count_tfidf_score,378,0.820251,0.145119,1.583467e-08,0.317589,0.102916,0.289966
18,expanded_0_70,0.70,count_tfidf_score,ESG_expanded_0_70_count_tfidf_score,378,0.751186,0.156998,1.712510e-06,0.316774,0.185617,0.056146
2,seed,NaN,count_tfidf_score,ESG_seed_count_tfidf_score,378,0.751459,0.175742,1.903371e-05,0.315863,0.183318,0.077756
22,expanded_0_80,0.80,count_tfidf_score,ESG_expanded_0_80_count_tfidf_score,378,0.751459,0.175742,1.903371e-05,0.315863,0.183318,0.077756
17,expanded_0_70,0.70,presence_count,ESG_expanded_0_70_presence_count,378,0.847571,0.073997,2.240803e-30,0.389967,0.216198,0.011405
9,expanded_0_60,0.60,presence_count,ESG_expanded_0_60_presence_count,378,0.896164,0.082146,1.038903e-27,0.383357,0.133088,0.149152
13,expanded_0_65,0.65,presence_count,ESG_expanded_0_65_presence_count,378,0.845586,0.078949,9.084513e-27,0.380414,0.197741,0.025097
1,seed,NaN,presence_count,ESG_seed_presence_count,378,0.756565,0.076555,4.951162e-23,0.359741,0.278706,0.001320
21,expanded_0_80,0.80,presence_count,ESG_expanded_0_80_presence_count,378,0.756565,0.076555,4.951162e-23,0.359741,0.278706,0.001320
5,expanded_0_55,0.55,presence_count,ESG_expanded_0_55_presence_count,378,0.854464,0.098368,3.741073e-18,0.344278,0.111719,0.263040
19,expanded_0_70,0.70,presence_tfidf_score,ESG_expanded_0_70_presence_tfidf_score,378,0.723830,0.080459,2.334573e-19,0.346887,0.293762,0.000584
3,seed,NaN,presence_tfidf_score,ESG_seed_presence_tfidf_score,378,0.721783,0.079677,1.318803e-19,0.339722,0.278175,0.001617
23,expanded_0_80,0.80,presence_tfidf_score,ESG_expanded_0_80_presence_tfidf_score,378,0.721783,0.079677,1.318803e-19,0.339722,0.278175,0.001617
15,expanded_0_65,0.65,presence_tfidf_score,ESG_expanded_0_65_presence_tfidf_score,378,0.685948,0.093185,1.822972e-13,0.327244,0.296217,0.000690
11,expanded_0_60,0.60,presence_tfidf_score,ESG_expanded_0_60_presence_tfidf_score,378,0.719746,0.099096,3.783211e-13,0.323219,0.240415,0.010349
7,expanded_0_55,0.55,presence_tfidf_score,ESG_expanded_0_55_presence_tfidf_score,378,0.613167,0.115357,1.064367e-07,0.288649,0.290525,0.004330

In [14]:
# Summarize threshold-level improvement relative to seed
seed_baseline = spearman_comparison_df[
    (spearman_comparison_df["dictionary_label"] == "seed")
    & (spearman_comparison_df["dimension"] == "ESG")
][["metric", "spearman_rho"]].rename(columns={"spearman_rho": "seed_spearman_rho"})

expanded_main = spearman_comparison_df[
    (spearman_comparison_df["dictionary_label"] != "seed")
    & (spearman_comparison_df["dimension"] == "ESG")
].merge(seed_baseline, on="metric", how="left")
expanded_main["rho_minus_seed"] = expanded_main["spearman_rho"] - expanded_main["seed_spearman_rho"]

analysis_summary_df = expanded_main.sort_values(["metric", "rho_minus_seed"], ascending=[True, False])
display(analysis_summary_df)

valid_spearman_df = analysis_summary_df.dropna(subset=["spearman_rho"])
if valid_spearman_df.empty:
    print("No valid expanded-dictionary Spearman results. Check whether analysis_df has matched ESG grades and non-constant score columns.")
    best_by_metric = pd.DataFrame(columns=["metric", "dictionary_label", "threshold", "feature", "spearman_rho", "seed_spearman_rho", "rho_minus_seed", "p_value"])
else:
    best_idx = valid_spearman_df.groupby("metric")["spearman_rho"].idxmax()
    best_by_metric = valid_spearman_df.loc[best_idx].sort_values("spearman_rho", ascending=False)

print("Best expanded dictionary by ESG Spearman for each metric")
display(best_by_metric[["metric", "dictionary_label", "threshold", "feature", "spearman_rho", "seed_spearman_rho", "rho_minus_seed", "p_value"]])

,dictionary_label,threshold,dimension,grade_col,metric,feature,n,spearman_rho,p_value,seed_spearman_rho,rho_minus_seed
0,expanded_0_80,0.80,ESG,esg_grade_num,count,ESG_expanded_0_80_count,378,0.719860,1.364310e-61,0.719860,0.000000
1,expanded_0_70,0.70,ESG,esg_grade_num,count,ESG_expanded_0_70_count,378,0.714937,2.119527e-60,0.719860,-0.004923
2,expanded_0_55,0.55,ESG,esg_grade_num,count,ESG_expanded_0_55_count,378,0.705889,2.825300e-58,0.719860,-0.013971
3,expanded_0_65,0.65,ESG,esg_grade_num,count,ESG_expanded_0_65_count,378,0.703765,8.671543e-58,0.719860,-0.016095
4,expanded_0_60,0.60,ESG,esg_grade_num,count,ESG_expanded_0_60_count,378,0.701950,2.242954e-57,0.719860,-0.017910
5,expanded_0_80,0.80,ESG,esg_grade_num,count_tfidf_score,ESG_expanded_0_80_count_tfidf_score,378,0.719589,1.589053e-61,0.719589,0.000000
6,expanded_0_70,0.70,ESG,esg_grade_num,count_tfidf_score,ESG_expanded_0_70_count_tfidf_score,378,0.712336,8.822280e-60,0.719589,-0.007254
7,expanded_0_55,0.55,ESG,esg_grade_num,count_tfidf_score,ESG_expanded_0_55_count_tfidf_score,378,0.707984,9.252479e-59,0.719589,-0.011605
8,expanded_0_65,0.65,ESG,esg_grade_num,count_tfidf_score,ESG_expanded_0_65_count_tfidf_score,378,0.702803,1.436595e-57,0.719589,-0.016786
9,expanded_0_60,0.60,ESG,esg_grade_num,count_tfidf_score,ESG_expanded_0_60_count_tfidf_score,378,0.702223,1.945107e-57,0.719589,-0.017366
10,expanded_0_60,0.60,ESG,esg_grade_num,presence_count,ESG_expanded_0_60_presence_count,378,0.650867,6.475150e-47,0.605798,0.045069
11,expanded_0_55,0.55,ESG,esg_grade_num,presence_count,ESG_expanded_0_55_presence_count,378,0.643900,1.212901e-45,0.605798,0.038102
12,expanded_0_65,0.65,ESG,esg_grade_num,presence_count,ESG_expanded_0_65_presence_count,378,0.641396,3.411819e-45,0.605798,0.035599
13,expanded_0_70,0.70,ESG,esg_grade_num,presence_count,ESG_expanded_0_70_presence_count,378,0.639017,9.038390e-45,0.605798,0.033220
14,expanded_0_80,0.80,ESG,esg_grade_num,presence_count,ESG_expanded_0_80_presence_count,378,0.605798,3.125205e-39,0.605798,0.000000
15,expanded_0_60,0.60,ESG,esg_grade_num,presence_tfidf_score,ESG_expanded_0_60_presence_tfidf_score,378,0.628180,6.868036e-43,0.602705,0.025475
16,expanded_0_55,0.55,ESG,esg_grade_num,presence_tfidf_score,ESG_expanded_0_55_presence_tfidf_score,378,0.625085,2.292938e-42,0.602705,0.022380
17,expanded_0_65,0.65,ESG,esg_grade_num,presence_tfidf_score,ESG_expanded_0_65_presence_tfidf_score,378,0.622006,7.506366e-42,0.602705,0.019301
18,expanded_0_70,0.70,ESG,esg_grade_num,presence_tfidf_score,ESG_expanded_0_70_presence_tfidf_score,378,0.618054,3.375193e-41,0.602705,0.015348
19,expanded_0_80,0.80,ESG,esg_grade_num,presence_tfidf_score,ESG_expanded_0_80_presence_tfidf_score,378,0.602705,9.498032e-39,0.602705,0.000000
20,expanded_0_65,0.65,ESG,esg_grade_num,share,ESG_expanded_0_65_share,378,0.046866,3.635309e-01,0.032721,0.014144
21,expanded_0_55,0.55,ESG,esg_grade_num,share,ESG_expanded_0_55_share,378,0.043700,3.968752e-01,0.032721,0.010979
22,expanded_0_70,0.70,ESG,esg_grade_num,share,ESG_expanded_0_70_share,378,0.042364,4.114816e-01,0.032721,0.009643
23,expanded_0_60,0.60,ESG,esg_grade_num,share,ESG_expanded_0_60_share,378,0.033446,5.167917e-01,0.032721,0.000725
24,expanded_0_80,0.80,ESG,esg_grade_num,share,ESG_expanded_0_80_share,378,0.032721,5.259251e-01,0.032721,0.000000

Best expanded dictionary by ESG Spearman for each metric

,metric,dictionary_label,threshold,feature,spearman_rho,seed_spearman_rho,rho_minus_seed,p_value
0,count,expanded_0_80,0.80,ESG_expanded_0_80_count,0.719860,0.719860,0.000000,1.364310e-61
5,count_tfidf_score,expanded_0_80,0.80,ESG_expanded_0_80_count_tfidf_score,0.719589,0.719589,0.000000,1.589053e-61
10,presence_count,expanded_0_60,0.60,ESG_expanded_0_60_presence_count,0.650867,0.605798,0.045069,6.475150e-47
15,presence_tfidf_score,expanded_0_60,0.60,ESG_expanded_0_60_presence_tfidf_score,0.628180,0.602705,0.025475,6.868036e-43
20,share,expanded_0_65,0.65,ESG_expanded_0_65_share,0.046866,0.032721,0.014144,3.635309e-01